version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./temp:/app/temp
    environment:
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - APP_ENV=${APP_ENV}
      - DEBUG=${DEBUG}
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: cerebras_app
      POSTGRES_USER: cerebras_user
      POSTGRES_PASSWORD: cerebras_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: